debug: true

server:
  port: 8083

spring:
  application:
    name: sms-service
  aop:
    auto: true
    proxy-target-class: false
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka