debug: true

server:
  port: 8080

spring:
  application:
    name: gateway-service
  # druid配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      poolPreparedStatements: true
    tomcat:
      url: jdbc:mysql://localhost:3306/fantablade?useUnicode=true&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  aop:
    auto: true
    proxy-target-class: false