debug: true

server:
  port: 8080

spring:
  application:
    name: gateway-service
  aop:
    auto: true
    proxy-target-class: false
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka
zuul:
  routes:
    api-order:
      path:
        /order/**
      serviceId:
        order-service